(function(){
  const isMainPage=()=>{const p=(location.pathname.split('/').pop()||'index.html').toLowerCase();return p==='index.html'||p===''};
  const page=()=>((location.pathname.split('/').pop()||'').toLowerCase());
  const isFramed=()=>{try{return window.top!==window.self}catch(_){return true}};
  const isProtectedDisplay=()=>['cast-10px.html','cast-v2.html','cast-ft-live.html','tv.html','tv-connect.html','dealer-access.html'].includes(page());
  const refreshThemeStylesheet=()=>{document.querySelectorAll('link[rel="stylesheet"]').forEach(link=>{const raw=link.getAttribute('href')||'';if(!/^app-theme\.css(?:\?|$)/.test(raw))return;link.href='app-theme.css?v=navfull0913'})};
  const ensureNavigationStyles=()=>{if(document.getElementById('stackup-global-nav-style-v2'))return;const style=document.createElement('style');style.id='stackup-global-nav-style-v2';style.textContent=`
html body #stackup-global-nav{position:relative!important;inset:auto!important;z-index:auto!important;display:grid!important;grid-template-columns:minmax(0,1fr)!important;gap:8px!important;width:100%!important;max-width:980px!important;margin:0 auto 12px!important;padding:12px 18px 0!important;box-sizing:border-box!important;background:transparent!important}
html body #stackup-global-nav #stackup-back,html body #stackup-global-nav #stackup-home{width:100%!important;max-width:100%!important;height:44px!important;min-height:44px!important;max-height:44px!important;padding:0 12px!important;margin:0!important;display:flex!important;align-items:center!important;justify-content:center!important;background:linear-gradient(#0B100D,#060907)!important;background-color:#060907!important;color:#8DFC3B!important;border:1px solid #8DFC3B!important;border-radius:9px!important;box-shadow:none!important;text-decoration:none!important;font-family:'Caacupe One',system-ui,sans-serif!important;font-style:normal!important;font-weight:300!important;font-size:14px!important;line-height:1!important;letter-spacing:1px!important;text-transform:uppercase!important;cursor:pointer!important}
@media(max-width:700px){html body #stackup-global-nav{padding-left:12px!important;padding-right:12px!important}}
`;document.head.appendChild(style)};
  const removeLegacyNavigation=()=>{const candidates=['.back[href="index.html"]','a.back[href$="index.html"]','nav.dock a[href="index.html"]','nav.dock a[href$="index.html"]'];document.querySelectorAll(candidates.join(',')).forEach(el=>{if(el.closest('#stackup-global-nav'))return;el.style.display='none'})};
  const loadScript=(src,key)=>{const base=src.split('?')[0];const existing=[...document.scripts].find(s=>(s.getAttribute('src')||'').split('?')[0].endsWith(base));if(existing){existing.dataset[key]='1';return existing}const marked=document.querySelector(`script[data-${key}]`);if(marked)return marked;const s=document.createElement('script');s.src=src;s.defer=true;s.dataset[key]='1';document.head.appendChild(s);return s};
  const loadSetupLayers=()=>{if(page()!=='setup.html')return;loadScript('structure-history-select.js?v=publication0914','structureSelector');loadScript('tournament-history.js?v=publication0914','tournamentHistory');loadScript('ranking-hierarchy-setup-v1.js?v=hierarchy0915','rankingHierarchySetup')};
  const setupPageFixes=()=>{if(page()!=='setup.html'||document.documentElement.dataset.setupFixes==='1')return;document.documentElement.dataset.setupFixes='1';const style=document.createElement('style');style.textContent=`#timeButtons button[data-time].active{background:#8DFC3B!important;color:#020302!important;border-color:#8DFC3B!important}`;document.head.appendChild(style)};
  const loadPublicationLayers=()=>{const p=page();loadScript('inline-interactions-v1.js?v=9e739887','inlineInteractions');loadScript('clickable-list-drawer-v1.js?v=05b98c8f','clickableListDrawer');loadScript('balancing-scope-guard-v1.js?v=scope0916','balancingScopeGuard');if(p==='tournament-readiness.html')loadScript('tournament-readiness-scope-v1.js?v=scope0916','tournamentReadinessScope');if(p==='tournament-manager.html'){loadScript('tournament-manager-audit-v1.js?v=publication0914','tournamentManagerAudit');loadScript('ranking-hierarchy-manager-v1.js?v=hierarchy0915','rankingHierarchyManager')}if(['checkin.html','pre-registration.html','smart-registration.html'].includes(p))loadScript('tournament-validation-gate-v1.js?v=publication0914','tournamentValidationGate');if(p==='checkin.html')loadScript('checkin-directory-select-v1.js?v=publication0914','checkinDirectorySelect');if(['wallet.html','finance.html','finance-settings.html','crm.html','communications.html','bounty.html','tournament-close.html'].includes(p))loadScript('sensitive-auth-guard-v1.js?v=publication0914','sensitiveAuthGuard');if(p==='finance-settings.html')loadScript('save-action-labels-v1.js?v=save0915','saveActionLabels');if(p.startsWith('ranking'))loadScript('app-language-ranking-v1.js?v=rankinglang0915','rankingLanguage');if(p==='tournament-close.html')loadScript('ranking-snapshot-v1.js?v=hierarchy0915','rankingSnapshot')};
  const navigation=()=>{if(!document.body||isMainPage()||isProtectedDisplay()||isFramed())return;ensureNavigationStyles();let nav=document.getElementById('stackup-global-nav');if(!nav){nav=document.createElement('nav');nav.id='stackup-global-nav';nav.setAttribute('aria-label','NAVEGAÇÃO GLOBAL');document.body.insertBefore(nav,document.body.firstChild)}nav.innerHTML='<button type="button" id="stackup-back">ANTERIOR</button><button type="button" id="stackup-home">MENU PRINCIPAL</button>';document.getElementById('stackup-back').onclick=()=>{if(history.length>1)history.back();else location.href='index.html'};document.getElementById('stackup-home').onclick=()=>{location.href='index.html'};removeLegacyNavigation()};
  const boot=()=>{if(isMainPage()||isProtectedDisplay())return;refreshThemeStylesheet();if(!isFramed()){ensureNavigationStyles();navigation();removeLegacyNavigation()}loadSetupLayers();setupPageFixes();loadPublicationLayers()};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();