(function(){
  const ELIGIBILITY_KEY='stackup-tournament-bonus-eligibility-v1';
  const page=(location.pathname.split('/').pop()||'').toLowerCase();
  const nowId=()=> 'bonus-'+Date.now()+'-'+Math.random().toString(36).slice(2,7);
  const normalizeCode=v=>String(v||'').toUpperCase();
  function ensure(){if(typeof ensureOperationalState==='function')ensureOperationalState();if(!Array.isArray(state.transactions))state.transactions=[];if(!Array.isArray(state.players))state.players=[]}
  function loadEligibility(){try{const d=JSON.parse(localStorage.getItem(ELIGIBILITY_KEY)||'{}');return d&&typeof d==='object'?d:{}}catch(_){return{}}}
  function saveEligibility(d){localStorage.setItem(ELIGIBILITY_KEY,JSON.stringify(d))}
  function eligibilityKey(directoryId,eventId=state.eventId){return String(eventId||'')+':'+String(directoryId||'')}
  function getEligibility(directoryId){const d=loadEligibility()[eligibilityKey(directoryId)]||{};return{early:!!d.early,addon:!!d.addon}}
  function setEligibility(directoryId,patch){const all=loadEligibility(),k=eligibilityKey(directoryId),old=all[k]||{};all[k]={...old,...patch,updatedAt:Date.now()};saveEligibility(all);return all[k]}
  function validBonusTx(){ensure();return state.transactions.filter(t=>t.eventId===state.eventId&&t.type==='BONUS'&&t.status!=='cancelled'&&t.status!=='void')}
  function hasBonus(playerId,code){return validBonusTx().some(t=>String(t.playerId)===String(playerId)&&normalizeCode(t.itemCode||t.payment?.reference)===code)}
  function counts(){const tx=validBonusTx();return{early:tx.filter(t=>normalizeCode(t.itemCode||t.payment?.reference)==='EARLY_BONUS').length,addon:tx.filter(t=>normalizeCode(t.itemCode||t.payment?.reference)==='ADDON_BONUS').length}}
  function addBonusTransaction(p,code,value,chips,source){if(hasBonus(p.id,code))return null;const tx={id:nowId(),eventId:state.eventId,operator:state.operator||'LOCAL',playerId:p.id,playerName:p.name,type:'BONUS',itemCode:code,value:0,bonusValue:+value||0,bonusChips:+chips||0,createdAt:Date.now(),source,status:'confirmed',breakdown:{prize:0,fee:0,bounty:0,payout:0,total:0,classification:'BONUS'}};state.transactions.unshift(tx);if(typeof auditEvent==='function')auditEvent('PLAYER_BONUS_AWARDED',{playerId:p.id,bonusType:code,bonusValue:+value||0,bonusChips:+chips||0,source});return tx}
  function awardEarly(p,source='CHECKIN'){ensure();if(!p||!p.earlyBonusEligible||hasBonus(p.id,'EARLY_BONUS'))return null;const chips=+state.earlyBonusChips||0,tx=addBonusTransaction(p,'EARLY_BONUS',state.earlyBonusValue,chips,source);if(!tx)return null;p.earlyBonusAwarded=true;p.earlyBonusAwardedAt=tx.createdAt;p.earlyBonusChips=chips;p.initialStackChips=(+state.startingStack||0)+chips;p.stackChips=Math.max(+p.stackChips||0,p.initialStackChips);if(typeof saveState==='function')saveState();return tx}
  function awardAddon(p,source='MOVEMENTS_PANEL'){ensure();if(!p||!p.addonBonusEligible||hasBonus(p.id,'ADDON_BONUS'))return null;const chips=+state.addonBonusChips||0,tx=addBonusTransaction(p,'ADDON_BONUS',state.addonBonusValue,chips,source);if(!tx)return null;p.addonBonusAwarded=true;p.addonBonusAwardedAt=tx.createdAt;p.addonBonusChips=chips;p.stackChips=(+p.stackChips||(+state.startingStack||0)+(+p.earlyBonusChips||0))+chips;if(typeof saveState==='function')saveState();return tx}
  function applyToTournamentPlayer(p,directoryId){const e=getEligibility(directoryId);p.earlyBonusEligible=!!e.early;p.addonBonusEligible=!!e.addon;p.bonusEligibilitySetAt=Date.now();if(p.earlyBonusEligible)awardEarly(p,'CHECKIN');if(typeof saveState==='function')saveState();return p}
  function selectedDirectoryId(){return localStorage.getItem('stackup-checkin-selected-player')||''}
  function checkinUI(){const grid=[...document.querySelectorAll('.grid')].find(g=>[...g.children].some(c=>String(c.textContent||'').trim()==='CHECK-IN'));if(!grid||document.getElementById('bonusEligibilityRow'))return;const row=document.createElement('div');row.id='bonusEligibilityRow';row.style.display='grid';row.style.gridTemplateColumns='repeat(2,minmax(0,1fr))';row.style.gap='8px';row.style.gridColumn='1/-1';row.innerHTML='<button type="button" id="earlyBonusToggle" class="bonusEligibility">□ EARLY BONUS</button><button type="button" id="addonBonusToggle" class="bonusEligibility">□ ADD ON BONUS</button>';grid.appendChild(row);const style=document.createElement('style');style.textContent='.bonusEligibility{min-height:44px;border:1px solid #27342D!important;border-radius:9px!important;background:linear-gradient(#0B100D,#060907)!important;color:#AEB8B1!important;font-weight:700!important}.bonusEligibility.active{border-color:#8DFC3B!important;color:#8DFC3B!important;background:#0b1309!important}@media(max-width:620px){#bonusEligibilityRow{grid-template-columns:1fr 1fr!important}}';document.head.appendChild(style);function paint(){const id=selectedDirectoryId(),e=getEligibility(id),a=document.getElementById('earlyBonusToggle'),b=document.getElementById('addonBonusToggle');a.classList.toggle('active',e.early);b.classList.toggle('active',e.addon);a.textContent=(e.early?'■ ':'□ ')+'EARLY BONUS';b.textContent=(e.addon?'■ ':'□ ')+'ADD ON BONUS'}function toggle(kind){const id=selectedDirectoryId();if(!id)return alert('SELECIONE PRIMEIRO UM JOGADOR.');const e=getEligibility(id);setEligibility(id,{[kind]:!e[kind]});paint()}document.getElementById('earlyBonusToggle').onclick=()=>toggle('early');document.getElementById('addonBonusToggle').onclick=()=>toggle('addon');paint();window.addEventListener('storage',paint);const confirm=document.getElementById('confirmBuyin');if(confirm)confirm.addEventListener('click',()=>{const directoryId=selectedDirectoryId();setTimeout(()=>{ensure();const p=state.players.slice().reverse().find(x=>String(x.directoryId||'')===String(directoryId));if(p)applyToTournamentPlayer(p,directoryId)},0)})}
  function movementsUI(){
    const rosterBtn=document.getElementById('registeredListBtn');if(!rosterBtn)return;
    const sections=[...document.querySelectorAll('.section')],tablesSection=sections.find(s=>String(s.textContent||'').trim()==='MESAS E BALANCING');if(tablesSection&&rosterBtn.previousElementSibling!==tablesSection)tablesSection.insertAdjacentElement('beforebegin',rosterBtn);rosterBtn.onclick=()=>{location.href='tournament-players.html'};
    const roster=document.getElementById('roster');if(roster)roster.style.display='none';['registeredBtn','playerChooser','identification'].forEach(id=>{const el=document.getElementById(id);if(el)el.style.display='none'});const legacyFlow=document.getElementById('transactionPlayerFlow');if(legacyFlow)legacyFlow.remove();
    const DIRECTORY_KEY='stackup-player-directory-v1',MAIN_KEY='stackup-movements-selected-player',PKO_PRO_KEY='stackup-pko-pro-player',PKO_CONTRA_KEY='stackup-pko-contra-player';
    const directory=()=>{try{const a=JSON.parse(localStorage.getItem(DIRECTORY_KEY)||'[]');return Array.isArray(a)?a:[]}catch(_){return[]}};
    const directoryFor=p=>{const a=directory();return a.find(d=>String(d.id)===String(p?.directoryId))||a.find(d=>String(d.cpf||'')&&String(d.cpf)===String(p?.directoryCpf||''))||null};
    const displayBirth=v=>{if(/^\d{4}-\d{2}-\d{2}$/.test(v||'')){const[y,m,d]=v.split('-');return`${d} / ${m} / ${y}`}return v||'—'};
    const selected=()=>{try{return(state.players||[]).find(p=>String(p.id)===String(selectedPlayerId))||null}catch(_){return null}};
    const pkoPro=()=>{const id=localStorage.getItem(PKO_PRO_KEY)||'';return(state.players||[]).find(p=>String(p.id)===String(id))||null};
    const pkoContra=()=>{const id=localStorage.getItem(PKO_CONTRA_KEY)||'';return(state.players||[]).find(p=>String(p.id)===String(id))||null};
    const style=document.createElement('style');style.textContent='#movementPlayerData,#pkoContraData,#pkoProData{display:grid;grid-template-columns:1fr;gap:8px;margin-top:8px}.movementDataCard{min-height:58px;padding:9px 10px;border:1px solid #27342D;border-radius:9px;background:linear-gradient(#0B100D,#060907)}.movementDataCard .k{font-size:9px!important}.movementDataCard .v{margin-top:6px;font-size:11px!important;font-weight:700}.movementOps{display:grid;gap:8px;margin-top:8px}.movementConfirm{padding:10px 2px;color:#AEB8B1;font-size:11px}.movementOps button{min-height:44px!important}.movementOps .primary{background:#8DFC3B!important;color:#020302!important}.movementOps .subTitle{color:#8DFC3B;font-size:11px;font-weight:800;letter-spacing:.1em;margin-top:8px}';document.head.appendChild(style);
    const host=document.createElement('div');host.id='movementPlayerOps';host.innerHTML='<div id="movementPlayerData"></div><div class="movementOps"><div class="subTitle">ELIMINAÇÃO</div><div id="eliminationConfirm" class="movementConfirm">SELECIONE UM JOGADOR ACIMA.</div><button type="button" id="confirmElimination" class="primary">CONFIRMAR ELIMINAÇÃO</button><div class="subTitle">PKO</div><button type="button" id="pkoContra">PKO CONTRA</button><div id="pkoContraData"></div><div id="pkoContraConfirm" class="movementConfirm">PKO CONTRA: PROCURE E SELECIONE UM JOGADOR INSCRITO.</div><button type="button" id="pkoPro">PKO PRÓ</button><div id="pkoProData"></div><div id="pkoProConfirm" class="movementConfirm">PKO PRÓ: PROCURE E SELECIONE UM JOGADOR INSCRITO.</div><button type="button" id="confirmPko" class="primary">CONFIRMAR PKO</button><div id="movementOpsStatus" class="movementConfirm"></div></div>';rosterBtn.insertAdjacentElement('afterend',host);
    function cardsHtml(p){const d=directoryFor(p);return[['NOME COMPLETO',p?.name||d?.name||'—'],['CPF',d?.cpf||p?.directoryCpf||'—'],['DATA DE NASCIMENTO',displayBirth(d?.birth||p?.directoryBirth||'')],['TELEFONE',d?.phone||p?.phone||'—']].map(([k,v])=>`<div class="movementDataCard"><div class="k">${k}</div><div class="v">${String(v||'—')}</div></div>`).join('')}
    function refresh(){const p=selected(),contra=pkoContra(),pro=pkoPro();movementPlayerData.innerHTML=cardsHtml(p);eliminationConfirm.textContent=p?`CONFIRMAR MESA ${p.table||'—'} • POSIÇÃO ${p.seat||p.finishPosition||'—'}${p.status==='eliminated'?' • JOGADOR JÁ ELIMINADO':''}`:'SELECIONE UM JOGADOR EM JOGADORES INSCRITOS.';confirmElimination.disabled=!p||p.status!=='active';pkoContraData.innerHTML=cardsHtml(contra);pkoContraConfirm.textContent=contra?`PKO CONTRA: ${contra.name} • MESA ${contra.table||'—'} • POSIÇÃO ${contra.seat||contra.finishPosition||'—'}${contra.status!=='eliminated'?' • JOGADOR NÃO ESTÁ ELIMINADO':''}`:'PKO CONTRA: PROCURE E SELECIONE UM JOGADOR INSCRITO.';pkoProData.innerHTML=cardsHtml(pro);pkoProConfirm.textContent=pro?`PKO PRÓ: ${pro.name} • MESA ${pro.table||'—'} • POSIÇÃO ${pro.seat||pro.finishPosition||'—'}`:'PKO PRÓ: PROCURE E SELECIONE UM JOGADOR INSCRITO.';confirmPko.disabled=!contra||!pro||String(contra.id)===String(pro.id)||contra.status!=='eliminated'}
    confirmElimination.onclick=()=>{const p=selected();if(!p)return;const r=window.PokerOperations?.eliminatePlayer({playerId:p.id,staff:{id:'MOVEMENTS_PANEL',name:'MOVEMENTS PANEL',role:'TD'},source:'MOVEMENTS_ELIMINATION'});movementOpsStatus.textContent=r?.ok?`ELIMINAÇÃO DE ${p.name} CONFIRMADA.`:(r?.error||'NÃO FOI POSSÍVEL CONFIRMAR A ELIMINAÇÃO.');if(r?.ok&&typeof renderAll==='function')renderAll();refresh()};
    pkoContra.onclick=()=>{location.href='tournament-players.html?mode=PKO_CONTRA'};
    pkoPro.onclick=()=>{location.href='tournament-players.html?mode=PKO_PRO'};
    confirmPko.onclick=()=>{const contra=pkoContra(),pro=pkoPro();if(!contra||!pro)return;if(String(contra.id)===String(pro.id))return movementOpsStatus.textContent='PKO PRÓ E PKO CONTRA NÃO PODEM SER O MESMO JOGADOR.';if(contra.status!=='eliminated')return movementOpsStatus.textContent='O JOGADOR PKO CONTRA PRECISA ESTAR ELIMINADO.';const r=window.PokerOperations?.awardBounty({winnerId:pro.id,eliminatedId:contra.id,staff:{id:'MOVEMENTS_PANEL',name:'MOVEMENTS PANEL',role:'TD'},source:'MOVEMENTS_PKO'});movementOpsStatus.textContent=r?.ok?`PKO CONFIRMADO: ${pro.name} SOBRE ${contra.name}.`:(r?.error||'NÃO FOI POSSÍVEL CONFIRMAR O PKO.');if(r?.ok){localStorage.removeItem(PKO_PRO_KEY);localStorage.removeItem(PKO_CONTRA_KEY);if(typeof renderAll==='function')renderAll()}refresh()};
    const selectedFromList=localStorage.getItem(MAIN_KEY);if(selectedFromList){try{selectedPlayerId=selectedFromList}catch(_){}if(typeof renderAll==='function')renderAll()}
    refresh();window.addEventListener('storage',refresh);const prev=window.onPokerStateChange;window.onPokerStateChange=s=>{if(typeof prev==='function')prev(s);refresh()};
    if(document.getElementById('addonBonusNotice'))return;const items=document.querySelector('.items');if(!items)return;const itemHost=items.closest('.fieldCard');const notice=document.createElement('div');notice.id='addonBonusNotice';notice.style.display='none';notice.style.marginTop='8px';notice.style.padding='10px 0';notice.style.borderTop='1px solid #27342D';notice.innerHTML='<div style="color:#8DFC3B;font-size:10px;font-weight:800;letter-spacing:.1em">ADD ON BONUS</div><div id="addonBonusNoticeText" style="color:#AEB8B1;font-size:10px;line-height:1.5;margin-top:4px"></div><button type="button" id="releaseAddonBonus" style="margin-top:8px">LIBERAR ADD ON BONUS</button>';itemHost.appendChild(notice);let chosenPlayerId='',chosenItem='';function refreshBonus(){ensure();const p=(state.players||[]).find(x=>String(x.id)===String(chosenPlayerId)),addon=/^ADDON_/.test(chosenItem),eligible=!!p?.addonBonusEligible,awarded=p?hasBonus(p.id,'ADDON_BONUS'):false;notice.style.display=addon&&eligible&&!awarded?'block':'none';if(addon&&eligible&&!awarded)document.getElementById('addonBonusNoticeText').textContent=`${p.name} TEM DIREITO AO ADD ON BONUS. O GESTOR DEVE LIBERAR ${(+state.addonBonusChips||0).toLocaleString('pt-BR')} FICHAS ADICIONAIS.`}document.addEventListener('click',e=>{const ib=e.target.closest('.item[data-item]');if(ib){chosenPlayerId=selected()?.id||'';chosenItem=ib.dataset.item;setTimeout(refreshBonus,0)}});document.getElementById('releaseAddonBonus').onclick=()=>{const p=(state.players||[]).find(x=>String(x.id)===String(chosenPlayerId));if(!p)return;if(!p.addonBonusEligible)return alert('JOGADOR SEM DIREITO AO ADD ON BONUS.');const tx=awardAddon(p,'MOVEMENTS_PANEL');if(!tx)return alert('ADD ON BONUS JÁ LIBERADO.');alert(`ADD ON BONUS LIBERADO: ${(+tx.bonusChips||0).toLocaleString('pt-BR')} FICHAS.`);refreshBonus()}
  }
  function castUI(){const el=document.getElementById('bonus');if(!el)return;const paint=()=>{const c=counts();el.textContent=`${c.early} / ${c.addon}`;const total=document.getElementById('totalStack');if(total){const active=(state.players||[]).filter(p=>p.status==='active');const chips=active.reduce((sum,p)=>sum+(+p.stackChips||(+state.startingStack||0)+(+p.earlyBonusChips||0)+(+p.addonBonusChips||0)),0);total.textContent=chips.toLocaleString('pt-BR')}};paint();setInterval(paint,200);window.addEventListener('storage',paint)}
  function boot(){if(typeof state==='undefined')return setTimeout(boot,50);ensure();if(page==='checkin.html')checkinUI();if(page==='players.html')movementsUI();if(page==='cast-10px.html')castUI()}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
  window.StackupBonus={ELIGIBILITY_KEY,getEligibility,setEligibility,counts,hasBonus,awardEarly,awardAddon,applyToTournamentPlayer};
})();