(function(){
  const KEY='stackup-finance-settings-v1';
  const CURRENCIES={BRL:{label:'REAL',symbol:'R$'},PYG:{label:'GUARANI',symbol:'₲'},USD:{label:'DÓLAR',symbol:'US$'},ARS:{label:'PESO ARGENTINO',symbol:'AR$'},EUR:{label:'EURO',symbol:'€'}};
  const BANKS={BR:{label:'BANCO CENTRAL DO BRASIL'},PY:{label:'BANCO CENTRAL DEL PARAGUAY'},US:{label:'FEDERAL RESERVE'},AR:{label:'BANCO CENTRAL DE LA REPÚBLICA ARGENTINA'},EU:{label:'BANCO CENTRAL EUROPEU'}};
  const FEE_CODES={PROCESSING:'PIX / CARTÃO',CROSS_EVENT_BUYIN:'BUY-IN OUTRO EVENTO',FIRST_REBUY:'PRIMEIRO REBUY',FIRST_REENTRY:'PRIMEIRA RE-ENTRY',FIRST_ADDON:'PRIMEIRO ADD-ON',EXPIRY:'PLAYER CREDIT +5 DIAS'};
  function blankWaivers(){return{PROCESSING:false,CROSS_EVENT_BUYIN:false,FIRST_REBUY:false,FIRST_REENTRY:false,FIRST_ADDON:false,EXPIRY:false}}
  function defaults(){return{closingCurrency:'BRL',centralBank:'BR',ratesToBRL:{BRL:1,PYG:0,USD:0,ARS:0,EUR:0},updatedAt:null,rateDate:'',sourceNote:'COTAÇÕES OFICIAIS DO BANCO CENTRAL SELECIONADO',feePolicy:{processingUsd:1,crossEventBuyinPct:10,firstRebuyPct:5,firstReentryPct:5,firstAddonPct:5,expiryPct:15},classificationWaivers:{STANDART:blankWaivers(),PREMIUM:blankWaivers(),DIAMANTE:blankWaivers()},playerFeeRules:{}}}
  function normalizeWaivers(v){return{...blankWaivers(),...(v||{})}}
  function load(){let cfg;try{cfg=JSON.parse(localStorage.getItem(KEY)||'null')}catch(e){cfg=null}const d=defaults();cfg={...d,...(cfg||{})};cfg.ratesToBRL={...d.ratesToBRL,...(cfg.ratesToBRL||{}),BRL:1};cfg.feePolicy={...d.feePolicy,...(cfg.feePolicy||{}),processingUsd:1};delete cfg.feePolicy.pixPct;delete cfg.feePolicy.cardPct;delete cfg.feePolicy.pixCardUsd;cfg.classificationWaivers={STANDART:normalizeWaivers(cfg.classificationWaivers?.STANDART),PREMIUM:normalizeWaivers(cfg.classificationWaivers?.PREMIUM),DIAMANTE:normalizeWaivers(cfg.classificationWaivers?.DIAMANTE)};cfg.playerFeeRules=cfg.playerFeeRules&&typeof cfg.playerFeeRules==='object'?cfg.playerFeeRules:{};return cfg}
  function save(cfg){const current=load();cfg={...current,...cfg,ratesToBRL:{...current.ratesToBRL,...(cfg.ratesToBRL||{}),BRL:1},feePolicy:{...current.feePolicy,...(cfg.feePolicy||{}),processingUsd:1},updatedAt:Date.now()};delete cfg.feePolicy.pixPct;delete cfg.feePolicy.cardPct;delete cfg.feePolicy.pixCardUsd;localStorage.setItem(KEY,JSON.stringify(cfg));window.dispatchEvent(new CustomEvent('stackup-finance-settings-change',{detail:cfg}));return cfg}
  function rateToBRL(currency,cfg=load()){if(currency==='BRL')return 1;const r=+cfg.ratesToBRL?.[currency]||0;return r>0?r:null}
  function convert(value,from,to,cfg=load()){const n=+value||0;if(from===to)return n;const a=rateToBRL(from,cfg),b=rateToBRL(to,cfg);if(a===null||b===null)return null;return n*a/b}
  function format(value,currency){const c=CURRENCIES[currency]||CURRENCIES.BRL,digits=currency==='PYG'?0:2;return `${c.symbol} ${Number(value||0).toLocaleString('pt-BR',{minimumFractionDigits:digits,maximumFractionDigits:digits})}`}
  function playerKey(player){return String(player?.directoryId||player?.id||'')}
  function playerRule(player,cfg=load()){const key=playerKey(player),saved=key?cfg.playerFeeRules?.[key]:null;return{classification:saved?.classification||player?.customerClass||'STANDART',waive:normalizeWaivers(saved?.waive)}}
  function feeWaived(player,feeCode,cfg=load()){const rule=playerRule(player,cfg),byClass=normalizeWaivers(cfg.classificationWaivers?.[rule.classification]);return !!(rule.waive?.[feeCode]||byClass?.[feeCode])}
  function paymentFee(_amount,method,cfg=load(),currency='BRL'){if(!['PIX','CARD'].includes(method))return 0;return convert(+cfg.feePolicy?.processingUsd||1,'USD',currency,cfg)}
  function processingFee(method,currency,player=null,cfg=load(),operationAmount=0){if(!['PIX','CARD'].includes(method)||feeWaived(player,'PROCESSING',cfg))return{rate:0,amount:0,currency,waived:true,fixedUsd:0};const fixedUsd=+cfg.feePolicy?.processingUsd||1,amount=convert(fixedUsd,'USD',currency,cfg);if(amount===null)return{rate:null,amount:null,currency,waived:false,fixedUsd,missingRate:'USD'};const rate=(+operationAmount||0)>0?amount/(+operationAmount):0;return{rate,amount,currency,waived:false,fixedUsd}}
  function paymentRecord({method,currency,amount,context='CHECKIN',status='PAID',reference='',player=null}){const cfg=load(),base=+amount||0,proc=processingFee(method,currency,player,cfg,base),processingFeeAmount=proc.amount,totalAmount=processingFeeAmount===null?null:base+processingFeeAmount,closingValue=convert(base,currency,cfg.closingCurrency,cfg),processingFeeClosingValue=processingFeeAmount===null?null:convert(processingFeeAmount,currency,cfg.closingCurrency,cfg),totalClosingValue=closingValue===null||processingFeeClosingValue===null?null:closingValue+processingFeeClosingValue;return{method,currency,amount:base,status,reference,context,closingCurrency:cfg.closingCurrency,closingValue,processingFeeRate:proc.rate,processingFeeAmount,processingFeeClosingValue,totalAmount,totalClosingValue,processingFeeWaived:proc.waived,processingFeeFixedUsd:proc.fixedUsd||0,playerKey:playerKey(player),centralBank:cfg.centralBank,rateDate:cfg.rateDate||'',rateSnapshot:{...cfg.ratesToBRL},recordedAt:Date.now()}}
  function installCashPaymentControl(){const grid=document.querySelector('.payGrid');if(!grid||grid.querySelector('[data-pay="CASH"]'))return;const button=document.createElement('button');button.type='button';button.className='pay';button.dataset.pay='CASH';button.textContent='DINHEIRO';const credit=grid.querySelector('[data-pay="PLAYER_CREDIT"]');grid.insertBefore(button,credit||null)}
  window.StackupFinance={KEY,CURRENCIES,BANKS,FEE_CODES,defaults,load,save,convert,format,playerKey,playerRule,feeWaived,paymentFee,processingFee,paymentRecord};
  installCashPaymentControl();
  if(!document.querySelector('script[data-stackup-data-entry]')){const s=document.createElement('script');s.src='data-entry-standard.js?v=publication0914';s.defer=true;s.dataset.stackupDataEntry='1';(document.head||document.documentElement).appendChild(s)}
})();