(()=>{
'use strict';
const norm=v=>String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').trim().toLocaleUpperCase('pt-BR');
const clone=v=>v===undefined?undefined:JSON.parse(JSON.stringify(v));
const hash=s=>{let h=2166136261;for(const ch of String(s)){h^=ch.charCodeAt(0);h=Math.imul(h,16777619)}return(h>>>0).toString(36)};
const eventOf=p=>String(p?.eventId||p?.validationEventId||'');
function ensure(){if(typeof state==='undefined')return;state.rankingRules=Array.isArray(state.rankingRules)?state.rankingRules:[];state.eventClosures=Array.isArray(state.eventClosures)?state.eventClosures:[];state.savedTournaments=Array.isArray(state.savedTournaments)?state.savedTournaments:[];state.authClubs=Array.isArray(state.authClubs)?state.authClubs:[];state.rankingStageMeta=state.rankingStageMeta&&typeof state.rankingStageMeta==='object'&&!Array.isArray(state.rankingStageMeta)?state.rankingStageMeta:{}}
function metaFor(src={}){ensure();const d=src.data||src.raw?.data||{},id=String(src.stageId||d.stageId||src.eventId||d.eventId||src.id||'');return state.rankingStageMeta?.[id]||{}}
function environment(src={}){const d=src.data||src.raw?.data||{},m=metaFor(src);const id=String(src.environmentId||d.environmentId||d.clubId||src.clubId||m.environmentId||'');const name=String(src.environmentName||d.environmentName||d.clubName||src.clubName||m.environmentName||'');const type=String(src.environmentType||d.environmentType||d.clubType||src.clubType||m.environmentType||'CLUB').toUpperCase();return{id,name,type}}
function tournamentName(src={}){const d=src.data||src.raw?.data||{},m=metaFor(src);return String(src.rankingTournamentName||d.rankingTournamentName||m.tournamentName||d.tournamentName||src.tournamentName||src.name||'TORNEIO').trim()}
function tournamentId(src={}){const d=src.data||src.raw?.data||{},m=metaFor(src),env=environment(src),name=tournamentName(src);return String(src.rankingTournamentId||d.rankingTournamentId||m.tournamentId||('ranking-tournament-'+hash(`${env.id||env.name}|${norm(name)}`)))}
function stageName(src={}){const d=src.data||src.raw?.data||{},m=metaFor(src);return String(src.stageName||d.stageName||m.stageName||'ETAPA ÚNICA').trim()||'ETAPA ÚNICA'}
function stageId(src={}){const d=src.data||src.raw?.data||{};return String(src.stageId||d.stageId||src.eventId||d.eventId||src.id||('stage-'+hash(`${tournamentId(src)}|${norm(stageName(src))}`)))}
function hierarchyMeta({eventId='',environmentId='',environmentName='',environmentType='',tournamentName='',stageName=''}){ensure();const tid='ranking-tournament-'+hash(`${environmentId||environmentName}|${norm(tournamentName)}`),sid=String(eventId||('stage-'+hash(`${tid}|${norm(stageName||'ETAPA ÚNICA')}`)));return{stageId:sid,stageName:String(stageName||'ETAPA ÚNICA').trim()||'ETAPA ÚNICA',tournamentId:tid,tournamentName:String(tournamentName||'TORNEIO').trim(),environmentId:String(environmentId||''),environmentName:String(environmentName||''),environmentType:String(environmentType||'CLUB').toUpperCase()}}
function explicitPoints(row,event){const r=(state.rankings||[]).find(x=>String(x.eventId||event)===String(event)&&(String(x.playerId||'')===String(row.playerId||row.id||'')||(row.directoryId&&String(x.directoryId||'')===String(row.directoryId))));if(r&&Number.isFinite(Number(r.points)))return Number(r.points);if(Number.isFinite(Number(row.points))&&Number(row.points)!==0)return Number(row.points);if(Number.isFinite(Number(row.rankingPoints))&&Number(row.rankingPoints)!==0)return Number(row.rankingPoints);return 0}
function liveRows(event){return(state.players||[]).filter(p=>eventOf(p)===String(event)).map(p=>({playerId:p.id,directoryId:p.directoryId||'',directoryCpf:p.directoryCpf||p.cpf||'',name:p.name||p.playerName||'JOGADOR',finishPosition:p.finishPosition||null,points:explicitPoints(p,event)}))}
function stages({includeDraft=false}={}){ensure();const out=new Map();for(const c of state.eventClosures){if(!c?.eventId)continue;const env=environment(c),tid=tournamentId(c),sid=stageId(c);out.set(sid,{stageId:sid,stageName:stageName(c),eventId:String(c.eventId),tournamentId:tid,tournamentName:tournamentName(c),environmentId:env.id,environmentName:env.name,environmentType:env.type,at:+c.closedAt||0,status:'CLOSED',rows:Array.isArray(c.rankingRows)?clone(c.rankingRows):[]})}
const current=String(state.eventId||'');if(current&&!out.has(current)){const meta=state.rankingStageMeta?.[current]||{},env={id:String(state.activeEnvironmentId||state.clubId||meta.environmentId||''),name:String(state.activeEnvironmentName||state.clubName||meta.environmentName||''),type:String(state.activeEnvironmentType||state.clubType||meta.environmentType||'CLUB').toUpperCase()},src={environmentId:env.id,environmentName:env.name,environmentType:env.type,tournamentName:state.tournamentName,rankingTournamentName:state.rankingTournamentName||meta.tournamentName,rankingTournamentId:state.rankingTournamentId||meta.tournamentId,stageName:state.stageName||meta.stageName,eventId:current};out.set(current,{stageId:current,stageName:stageName(src),eventId:current,tournamentId:tournamentId(src),tournamentName:tournamentName(src),environmentId:env.id,environmentName:env.name,environmentType:env.type,at:Date.now(),status:state.tournamentStatus||state.status||'ACTIVE',rows:liveRows(current)})}
if(includeDraft){for(const t of state.savedTournaments){const d=t?.data||{},sid=String(t.id||stageId(t));if(out.has(sid))continue;const m=state.rankingStageMeta?.[sid]||{},env=environment({...d,id:sid}),src={...d,id:t.id,name:t.name,rankingTournamentName:m.tournamentName,rankingTournamentId:m.tournamentId,stageName:m.stageName};out.set(sid,{stageId:sid,stageName:stageName(src),eventId:sid,tournamentId:tournamentId(src),tournamentName:tournamentName(src),environmentId:env.id||m.environmentId,environmentName:env.name||m.environmentName,environmentType:env.type||m.environmentType,at:+t.updatedAt||0,status:t.status||'DRAFT',rows:[]})}}
return[...out.values()]}
function environments(){ensure();const map=new Map();state.authClubs.filter(x=>x&&x.active!==false).forEach(x=>map.set(String(x.id||x.name),{id:String(x.id||''),name:String(x.name||'AMBIENTE'),type:String(x.type||'CLUB').toUpperCase()}));stages({includeDraft:true}).forEach(s=>{const k=s.environmentId||s.environmentName;if(k&&!map.has(k))map.set(k,{id:s.environmentId,name:s.environmentName||'AMBIENTE',type:s.environmentType||'CLUB'})});return[...map.values()]}
function tournaments(environmentId=''){const map=new Map();stages({includeDraft:true}).filter(s=>!environmentId||String(s.environmentId)===String(environmentId)).forEach(s=>{if(!map.has(s.tournamentId))map.set(s.tournamentId,{id:s.tournamentId,name:s.tournamentName,environmentId:s.environmentId,environmentName:s.environmentName,environmentType:s.environmentType,stages:[]});map.get(s.tournamentId).stages.push(s)});return[...map.values()].sort((a,b)=>a.name.localeCompare(b.name,'pt-BR'))}
function ruleKey(environmentId,tournament=''){return `${environmentId||'GLOBAL'}::${tournament||'*'}`}
function findRule(environmentId,tournament=''){ensure();const exact=state.rankingRules.find(r=>r.active!==false&&String(r.environmentId||'')===String(environmentId||'')&&String(r.tournamentId||'')===String(tournament||''));if(exact)return exact;if(tournament)return state.rankingRules.find(r=>r.active!==false&&String(r.environmentId||'')===String(environmentId||'')&&!r.tournamentId)||null;return null}
function saveRule(rule){ensure();const data={id:rule.id||('ranking-rule-'+hash(ruleKey(rule.environmentId,rule.tournamentId))),active:true,environmentId:String(rule.environmentId||''),environmentName:String(rule.environmentName||''),scope:rule.tournamentId?'TOURNAMENT':'ORGANIZATION',tournamentId:String(rule.tournamentId||''),tournamentName:String(rule.tournamentName||''),participationPoints:Math.max(0,Number(rule.participationPoints)||0),bestStages:Math.max(0,Math.floor(Number(rule.bestStages)||0)),tieBreaker:String(rule.tieBreaker||'WINS'),points:{...(rule.points||{})},updatedAt:Date.now()};const ix=state.rankingRules.findIndex(x=>String(x.id)===String(data.id)||ruleKey(x.environmentId,x.tournamentId)===ruleKey(data.environmentId,data.tournamentId));if(ix>=0)state.rankingRules[ix]=data;else state.rankingRules.unshift(data);saveState();return data}
function deleteRule(environmentId,tournament=''){ensure();state.rankingRules=state.rankingRules.filter(r=>ruleKey(r.environmentId,r.tournamentId)!==ruleKey(environmentId,tournament));saveState()}
function pointsFor(row,stage){const rule=findRule(stage.environmentId,stage.tournamentId);if(rule&&row.finishPosition){const k=String(Math.max(1,Math.floor(Number(row.finishPosition)||0)));const has=Object.prototype.hasOwnProperty.call(rule.points||{},k);return(has?Number(rule.points[k])||0:0)+(Number(rule.participationPoints)||0)}if(rule)return(Number(rule.participationPoints)||0)+explicitPoints(row,stage.eventId);return explicitPoints(row,stage.eventId)}
function playerKey(p){return String(p.directoryId||p.directoryCpf||p.cpf||p.playerId||p.id||norm(p.name||''))}
function aggregate(stageList,scopeRule=null){const map=new Map();for(const s of stageList){for(const p of s.rows||[]){const k=playerKey(p);if(!k)continue;const pts=pointsFor(p,s),prev=map.get(k)||{key:k,name:p.name||'JOGADOR',points:0,stages:0,wins:0,podiums:0,bestFinish:999,results:[]};const finish=Number(p.finishPosition)||999;prev.results.push({stageId:s.stageId,stageName:s.stageName,tournamentId:s.tournamentId,tournamentName:s.tournamentName,points:pts,finishPosition:finish});prev.stages+=1;if(finish===1)prev.wins+=1;if(finish<=3)prev.podiums+=1;prev.bestFinish=Math.min(prev.bestFinish,finish);map.set(k,prev)}}const best=Math.max(0,Math.floor(Number(scopeRule?.bestStages)||0));for(const p of map.values()){const chosen=[...p.results].sort((a,b)=>b.points-a.points||a.finishPosition-b.finishPosition);p.points=chosen.slice(0,best||chosen.length).reduce((a,r)=>a+r.points,0);p.countedStages=best?Math.min(best,chosen.length):chosen.length}const tie=String(scopeRule?.tieBreaker||'WINS');return[...map.values()].sort((a,b)=>{if(b.points!==a.points)return b.points-a.points;if(tie==='BEST_FINISH'&&a.bestFinish!==b.bestFinish)return a.bestFinish-b.bestFinish;if(tie==='STAGES'&&b.stages!==a.stages)return b.stages-a.stages;if(b.wins!==a.wins)return b.wins-a.wins;if(b.podiums!==a.podiums)return b.podiums-a.podiums;if(a.bestFinish!==b.bestFinish)return a.bestFinish-b.bestFinish;return a.name.localeCompare(b.name,'pt-BR')})}
window.StackupRanking={ensure,environments,tournaments,stages,tournamentId,tournamentName,stageId,stageName,hierarchyMeta,findRule,saveRule,deleteRule,pointsFor,aggregate,ruleKey};
})();