(function(){
  function ensure(){ensureOperationalState();const now=Date.now();if(!Number.isFinite(+state.timerBaseRemaining))state.timerBaseRemaining=Math.max(0,+state.remaining||currentItem().duration||0);if(!Number.isFinite(+state.elapsedBase))state.elapsedBase=Math.max(0,+state.elapsed||0);if(state.running&&!state.timerStartedAt)state.timerStartedAt=now;if(state.running&&!state.elapsedStartedAt)state.elapsedStartedAt=now;if(state.running&&!state.startedAt)state.startedAt=now;if(!state.running){state.timerStartedAt=null;state.elapsedStartedAt=null}return state}
  function rawRemaining(now=Date.now()){ensure();let remaining=+state.timerBaseRemaining||0;if(state.running&&state.timerStartedAt)remaining-=Math.floor((now-state.timerStartedAt)/1000);return remaining}
  function snapshot(now=Date.now()){ensure();let remaining=Math.max(0,rawRemaining(now)),elapsed=Math.max(0,+state.elapsedBase||0);if(state.running&&state.elapsedStartedAt)elapsed+=Math.floor((now-state.elapsedStartedAt)/1000);return{remaining,elapsed,running:!!state.running,levelIndex:+state.levelIndex||0,item:currentItem()}}
  function commit(now=Date.now()){const s=snapshot(now);state.timerBaseRemaining=s.remaining;state.elapsedBase=s.elapsed;state.remaining=s.remaining;state.elapsed=s.elapsed;if(state.running){state.timerStartedAt=now;state.elapsedStartedAt=now}else{state.timerStartedAt=null;state.elapsedStartedAt=null}return s}
  function setRunning(on){ensure();commit();state.running=!!on;const now=Date.now();if(state.running){if(!state.startedAt)state.startedAt=now;state.timerStartedAt=now;state.elapsedStartedAt=now}else{state.timerStartedAt=null;state.elapsedStartedAt=null}auditEvent(state.running?'TIMER_STARTED':'TIMER_PAUSED',{source:'TIMER_ENGINE'});saveState();return snapshot()}
  function toggle(){return setRunning(!state.running)}
  function setRemaining(sec){commit();const v=Math.max(0,Math.floor(+sec||0));state.timerBaseRemaining=v;state.remaining=v;if(state.running)state.timerStartedAt=Date.now();saveState();return snapshot()}
  function adjust(seconds){const s=snapshot();return setRemaining(s.remaining+(+seconds||0))}
  function setIndex(index,{transition=true,remainingOverride=null,now=Date.now()}={}){commit(now);const max=Math.max(0,(state.structure||[]).length-1),next=Math.max(0,Math.min(max,+index||0));state.levelIndex=next;const item=currentItem();const nextRemaining=remainingOverride===null?Math.max(0,+item.duration||0):Math.max(0,+remainingOverride||0);state.timerBaseRemaining=nextRemaining;state.remaining=nextRemaining;if(state.running)state.timerStartedAt=now;if(transition){state.transition={createdAt:Date.now(),kind:item.type==='break'?'break':'level',title:item.type==='break'?(item.label||'BREAK'):(item.label||'NÍVEL'),subtitle:item.type==='level'?`SB ${fmtNumber(item.sb)} / BB ${fmtNumber(item.bb)} / ANTE ${fmtNumber(item.ante)}`:'INTERVALO'};auditEvent(item.type==='break'?'BREAK_STARTED':'LEVEL_CHANGED',{levelIndex:state.levelIndex,label:item.label,source:'TIMER_ENGINE'})}saveState();return snapshot(now)}
  function next(){return setIndex((+state.levelIndex||0)+1)}
  function prev(){return setIndex((+state.levelIndex||0)-1)}
  function resetLevel(){return setIndex(+state.levelIndex||0,{transition:false})}
  function advanceIfNeeded(now=Date.now()){ensure();if(state.finalTableMode==='HANDS')return snapshot(now);if(!state.running)return snapshot(now);let raw=rawRemaining(now);if(raw>0)return snapshot(now);let overdue=Math.max(0,-raw),idx=+state.levelIndex||0,guard=100;const elapsed=snapshot(now).elapsed;while(guard--){if(idx>=(state.structure||[]).length-1){state.levelIndex=idx;state.timerBaseRemaining=0;state.remaining=0;state.elapsedBase=elapsed;state.elapsed=elapsed;state.running=false;state.timerStartedAt=null;state.elapsedStartedAt=null;auditEvent('TIMER_FINISHED',{source:'TIMER_ENGINE'});saveState();return snapshot(now)}idx+=1;const item=state.structure[idx],duration=Math.max(0,+item.duration||0);state.levelIndex=idx;state.transition={createdAt:Date.now(),kind:item.type==='break'?'break':'level',title:item.type==='break'?(item.label||'BREAK'):(item.label||'NÍVEL'),subtitle:item.type==='level'?`SB ${fmtNumber(item.sb)} / BB ${fmtNumber(item.bb)} / ANTE ${fmtNumber(item.ante)}`:'INTERVALO'};auditEvent(item.type==='break'?'BREAK_STARTED':'LEVEL_CHANGED',{levelIndex:idx,label:item.label,source:'TIMER_ENGINE',recovered:true});if(overdue<duration){state.timerBaseRemaining=duration-overdue;state.remaining=duration-overdue;state.elapsedBase=elapsed;state.elapsed=elapsed;state.timerStartedAt=now;state.elapsedStartedAt=now;saveState();return snapshot(now)}overdue-=duration}return snapshot(now)}
  function authorityTick(){const s=advanceIfNeeded();state.remaining=s.remaining;state.elapsed=s.elapsed;return s}
  function displayed(){return snapshot()}
  window.TournamentTimer={ensure,rawRemaining,snapshot,commit,setRunning,toggle,setRemaining,adjust,setIndex,next,prev,resetLevel,advanceIfNeeded,authorityTick,displayed};ensure();
})();

if(/(?:^|\/)broadcast\.html$/i.test(location.pathname)){
  const script=document.createElement('script');
  script.src='broadcast-layout.js?v=layout-studio-1';
  script.defer=true;
  document.head.appendChild(script);
}
