(function(){
  'use strict';
  const page=(location.pathname.split('/').pop()||'').toLowerCase();
  if(page!=='setup.html')return;
  const STYLE_ID='stackup-tournament-history-style';
  const CONFIG_KEYS=['clubName','clubId','clubType','language','tournamentFormat','gameType','seatsPerTable','buyin','buyinChips','earlyBonusValue','earlyBonusChips','rebuyValue','rebuyChips','doubleRebuyValue','doubleRebuyChips','reentryValue','reentryChips','addonValue','addonChips','specialAddonValue','specialAddonChips','addonBonusValue','addonBonusChips','bountyValue','bountyRecurring','bountyDoubleSecond','bountyOnReentry','fee','guaranteed','paidPlaces','lateRegLevel','startingStack','structure','selectedStructureId','selectedStructureName','finalTableStructureMode','finalTableHandsPerLevel','announcements'];
  const clone=v=>v===undefined?undefined:JSON.parse(JSON.stringify(v));
  const esc=v=>String(v||'').replace(/[<>]/g,'');
  const ensureState=()=>{if(!Array.isArray(state.savedTournaments))state.savedTournaments=[];if(typeof state.selectedTournamentId!=='string')state.selectedTournamentId='';if(typeof state.selectedTournamentName!=='string')state.selectedTournamentName=''};
  const snapshot=()=>{const out={};CONFIG_KEYS.forEach(k=>{if(state[k]!==undefined)out[k]=clone(state[k])});out.tournamentName=String(document.getElementById('tournamentName')?.value||state.tournamentName||'').trim();return out};
  const selectedTournament=()=>state.savedTournaments.find(t=>String(t.id)===String(state.selectedTournamentId))||null;
  const applySnapshot=t=>{if(!t||!t.data)return false;CONFIG_KEYS.forEach(k=>{if(Object.prototype.hasOwnProperty.call(t.data,k))state[k]=clone(t.data[k])});state.tournamentName=t.name||t.data.tournamentName||'';state.selectedTournamentId=t.id;state.selectedTournamentName=t.name||'';state.prepared=false;state.status='DRAFT';state.tournamentStatus='DRAFT';saveState();if(typeof render==='function')render();if(typeof renderSummary==='function')renderSummary();showSelectedTournament();return true};
  const addStyle=()=>{if(document.getElementById(STYLE_ID))return;const style=document.createElement('style');style.id=STYLE_ID;style.textContent=`
    .cta{display:none!important}
    .structureMenu{display:grid!important;grid-template-columns:minmax(0,1fr)!important;gap:8px!important;width:100%!important;align-items:stretch!important}
    .structureMenu>button{display:flex!important;align-items:center!important;justify-content:center!important;width:100%!important;min-width:0!important;height:48px!important;min-height:48px!important;max-height:48px!important;margin:0!important;padding:10px 12px!important;box-sizing:border-box!important;text-align:center!important}
    #setupDataActions{display:grid!important;grid-template-columns:1fr 1fr!important;gap:8px!important;margin:12px 0 16px!important}
    #setupDataActions button{min-height:48px!important;width:100%!important}
    #setupDataActions .hidden{display:none!important}
    #tournamentManager{margin-top:16px!important;width:100%!important}
    #tournamentActions{display:grid!important;grid-template-columns:minmax(0,1fr)!important;gap:8px!important;align-items:stretch!important;width:100%!important}
    #tournamentActions>button{display:flex!important;align-items:center!important;justify-content:center!important;width:100%!important;min-width:0!important;height:48px!important;min-height:48px!important;max-height:48px!important;margin:0!important;padding:10px 12px!important;box-sizing:border-box!important;text-align:center!important}
    #tournamentHistory{margin:0!important;padding:0!important;border:0!important;border-radius:0!important;background:transparent!important;box-shadow:none!important}
    #selectedTournamentName{margin:8px 0 0!important;padding:0!important;border:0!important;border-radius:0!important;background:transparent!important;box-shadow:none!important;color:#fff!important;font-weight:600!important}
    #selectedTournamentName b{color:#8DFC3B!important}
    #tournamentHistoryList{display:grid!important;gap:8px!important}
    .tournamentHistoryItem{display:grid!important;grid-template-columns:28px minmax(0,1fr) minmax(260px,auto)!important;gap:8px!important;align-items:center!important;padding:10px 0!important;border-bottom:1px solid #27342D!important}
    .tournamentHistoryActions{display:grid!important;grid-template-columns:repeat(3,minmax(0,1fr))!important;gap:8px!important}
    .tournamentHistoryActions button{min-height:44px!important}
    .tournamentSelectCheck{appearance:none!important;-webkit-appearance:none!important;width:20px!important;height:20px!important;min-width:20px!important;margin:0!important;border:1px solid #8DFC3B!important;border-radius:4px!important;background:#060907!important;box-sizing:border-box!important}
    .tournamentSelectCheck:checked{background:#8DFC3B!important;box-shadow:inset 0 0 0 4px #060907!important}
    .tournamentHistoryName{font-weight:600!important;color:#fff!important}
    .tournamentHistoryMeta{color:#AEB8B1!important;font-size:12px!important;margin-top:3px!important}
    @media(max-width:700px){.tournamentHistoryItem{grid-template-columns:28px minmax(0,1fr)!important}.tournamentHistoryActions{grid-column:2!important}.structureMenu{grid-template-columns:minmax(0,1fr)!important}#setupDataActions{grid-template-columns:1fr!important}}
  `;document.head.appendChild(style)};
  const manager=()=>{let box=document.getElementById('tournamentManager');if(box)return box;const oldCta=document.querySelector('.cta');if(!oldCta)return null;box=document.createElement('section');box.id='tournamentManager';box.innerHTML=`<div class="section">TORNEIO</div><div id="tournamentActions"><button type="button" id="saveTournamentBtn">SALVAR TORNEIO</button><button type="button" id="tournamentHistoryBtn">HISTÓRICO DE TORNEIOS</button><div id="tournamentHistory" class="hidden"><div id="tournamentHistoryList"></div></div></div><div id="selectedTournamentName" class="hidden"></div>`;oldCta.insertAdjacentElement('beforebegin',box);return box};
  function showSelectedTournament(){const row=document.getElementById('selectedTournamentName');if(!row)return;const t=selectedTournament();if(!t){row.classList.add('hidden');row.textContent='';return}row.innerHTML=`<b>TORNEIO SALVO:</b> ${esc(t.name||'TORNEIO')}`;row.classList.remove('hidden')}
  const saveTournament=()=>{const field=document.getElementById('tournamentName'),name=String(field?.value||state.tournamentName||'').trim();if(!name){alert('INFORME O NOME DO TORNEIO ANTES DE SALVAR.');field?.focus();return false}state.tournamentName=name;const existing=selectedTournament(),id=existing?existing.id:`tournament-${Date.now()}`,data={id,name,data:snapshot(),status:'DRAFT',updatedAt:Date.now()};const ix=state.savedTournaments.findIndex(t=>String(t.id)===String(id));if(ix>=0)state.savedTournaments[ix]=data;else state.savedTournaments.unshift(data);state.selectedTournamentId=id;state.selectedTournamentName=name;state.prepared=false;state.status='DRAFT';state.tournamentStatus='DRAFT';saveState();showSelectedTournament();renderHistory();const b=document.getElementById('saveTournamentBtn');if(b){b.textContent='TORNEIO SALVO';setTimeout(()=>{if(b.isConnected)b.textContent='SALVAR TORNEIO'},1000)}return true};
  const deleteTournament=id=>{const t=state.savedTournaments.find(x=>String(x.id)===String(id));if(t&&!confirm(`APAGAR ${t.name||'ESTE TORNEIO'}?`))return;state.savedTournaments=state.savedTournaments.filter(x=>String(x.id)!==String(id));if(String(state.selectedTournamentId)===String(id)){state.selectedTournamentId='';state.selectedTournamentName=''}saveState();showSelectedTournament();renderHistory()};
  function renderHistory(){const list=document.getElementById('tournamentHistoryList');if(!list)return;list.innerHTML='';if(!state.savedTournaments.length){list.innerHTML='<div class="muted">NENHUM TORNEIO SALVO.</div>';return}state.savedTournaments.forEach(t=>{const item=document.createElement('div');item.className='tournamentHistoryItem';const check=document.createElement('input');check.type='checkbox';check.className='tournamentSelectCheck';check.checked=String(state.selectedTournamentId)===String(t.id);check.onchange=()=>{if(check.checked)applySnapshot(t);else if(String(state.selectedTournamentId)===String(t.id)){state.selectedTournamentId='';state.selectedTournamentName='';saveState();showSelectedTournament()}renderHistory()};const info=document.createElement('div');info.innerHTML=`<div class="tournamentHistoryName">${esc(t.name)}</div><div class="tournamentHistoryMeta">${(t.data?.structure||[]).filter(x=>x.type==='level').length} NÍVEIS • ${esc(t.status||'DRAFT')}</div>`;const actions=document.createElement('div');actions.className='tournamentHistoryActions';['USAR','EDITAR','APAGAR'].forEach(label=>{const b=document.createElement('button');b.type='button';b.textContent=label;if(label==='USAR')b.onclick=()=>{if(applySnapshot(t)){document.getElementById('tournamentHistory').classList.add('hidden');renderHistory()}};if(label==='EDITAR')b.onclick=()=>{if(applySnapshot(t)){document.getElementById('tournamentHistory').classList.add('hidden');unlockSetupData();window.scrollTo({top:0,behavior:'smooth'})}};if(label==='APAGAR')b.onclick=()=>deleteTournament(t.id);actions.appendChild(b)});item.append(check,info,actions);list.appendChild(item)})}
  const bind=()=>{const history=document.getElementById('tournamentHistory');document.getElementById('saveTournamentBtn').onclick=saveTournament;document.getElementById('tournamentHistoryBtn').onclick=()=>{const opening=history.classList.contains('hidden');history.classList.toggle('hidden');if(opening)renderHistory()}};

  const SETUP_NUMERIC=['buyin','buyinChips','earlyBonusValue','earlyBonusChips','rebuyValue','rebuyChips','doubleRebuyValue','doubleRebuyChips','reentryValue','reentryChips','addonValue','addonChips','specialAddonValue','specialAddonChips','addonBonusValue','addonBonusChips','bountyValue','fee'];
  const SETUP_SELECT=['language','tournamentFormat','gameType','seatsPerTable'];
  const SETUP_TEXT=['clubName','tournamentName'];
  const SETUP_CHECK=['bountyRecurring','bountyDoubleSecond'];
  const setupFields=()=>[...SETUP_TEXT,...SETUP_SELECT,...SETUP_NUMERIC,...SETUP_CHECK].map(id=>document.getElementById(id)).filter(Boolean);
  const restoreSetupValues=()=>{SETUP_TEXT.forEach(id=>{const el=document.getElementById(id);if(el)el.value=state[id]||''});SETUP_SELECT.forEach(id=>{const el=document.getElementById(id);if(!el)return;const v=state[id];el.value=v===undefined||v===null?'':String(v)});SETUP_NUMERIC.forEach(id=>{const el=document.getElementById(id);if(el)el.value=(+state[id]||0)?String(+state[id]):''});SETUP_CHECK.forEach(id=>{const el=document.getElementById(id);if(el)el.checked=!!state[id]})};
  const setSetupLocked=locked=>{setupFields().forEach(el=>{if(el.matches('select,input[type="checkbox"]'))el.disabled=locked;else el.readOnly=locked});const confirm=document.getElementById('setupConfirmData'),edit=document.getElementById('setupEditData');if(confirm)confirm.classList.toggle('hidden',locked);if(edit)edit.classList.toggle('hidden',!locked)};
  const unlockSetupData=()=>{restoreSetupValues();setSetupLocked(false);document.getElementById('clubName')?.focus()};
  const confirmSetupData=()=>{SETUP_TEXT.forEach(id=>{const el=document.getElementById(id);if(el)state[id]=el.value.trim()});SETUP_SELECT.forEach(id=>{const el=document.getElementById(id);if(!el)return;state[id]=id==='seatsPerTable'?(+el.value||''):(el.value||'')});SETUP_NUMERIC.forEach(id=>{const el=document.getElementById(id);if(el)state[id]=Math.max(0,+el.value||0)});SETUP_CHECK.forEach(id=>{const el=document.getElementById(id);if(el)state[id]=!!el.checked});state.bountyOnReentry=!!state.bountyRecurring;saveState();if(typeof renderSummary==='function')renderSummary();setSetupLocked(true)};
  const directSetupInputs=()=>{if(document.getElementById('setupDataActions'))return;SETUP_NUMERIC.forEach(id=>{const el=document.getElementById(id);if(!el)return;el.readOnly=false;el.inputMode='decimal';el.onclick=null;el.onfocus=null});SETUP_TEXT.forEach(id=>{const el=document.getElementById(id);if(el)el.oninput=null});SETUP_SELECT.forEach(id=>{const el=document.getElementById(id);if(el)el.onchange=null});SETUP_CHECK.forEach(id=>{const el=document.getElementById(id);if(el)el.onchange=null});const structureHeading=[...document.querySelectorAll('.card')].find(card=>card.querySelector('.section')?.textContent.trim()==='ESTRUTURA DE NÍVEIS');if(!structureHeading)return;const actions=document.createElement('div');actions.id='setupDataActions';actions.innerHTML='<button id="setupConfirmData" class="primary" type="button">CONFIRMAR</button><button id="setupEditData" class="hidden" type="button">EDITAR DADOS</button>';structureHeading.insertAdjacentElement('beforebegin',actions);document.getElementById('setupConfirmData').onclick=confirmSetupData;document.getElementById('setupEditData').onclick=unlockSetupData;const legacyRender=typeof window.render==='function'?window.render:null;if(legacyRender&&!window.__stackupSetupRenderWrapped){window.__stackupSetupRenderWrapped=true;window.render=function(){legacyRender();restoreSetupValues()}}restoreSetupValues();setSetupLocked(false)};

  const boot=()=>{ensureState();const title=document.querySelector('.title');if(title)title.textContent='CONFIGURAÇÕES DO TORNEIO';document.title='CONFIGURAÇÕES DO TORNEIO • STACKUP';addStyle();if(!manager())return;bind();directSetupInputs();showSelectedTournament();renderHistory()};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();