(function(){
  const ALPHABET='ABCDEFGHJKLMNPQRSTUVWXYZ23456789';
  function normalizeCode(v){return String(v||'').toUpperCase().replace(/[^A-Z0-9]/g,'').trim()}
  function makeCode(){let s='';for(let i=0;i<6;i++)s+=ALPHABET[Math.floor(Math.random()*ALPHABET.length)];return s}
  function uniqueCode(player=null){let c;do{c=makeCode()}while((state.players||[]).some(x=>x!==player&&x.validationEventId===state.eventId&&normalizeCode(x.validationCode)===c));return c}
  function ensurePlayerValidationCode(player){if(!player)return null;if(!player.validationCode||player.validationEventId!==state.eventId){player.validationCode=uniqueCode(player);player.validationEventId=state.eventId}if(!player.validationCodeStatus)player.validationCodeStatus=player.status==='eliminated'?'INACTIVE':'ACTIVE';return player.validationCode}
  function ensureValidationState(){ensureOperationalState();if(!Array.isArray(state.validationLog))state.validationLog=[];(state.players||[]).forEach(ensurePlayerValidationCode)}
  function validationPlayerByCode(code){ensureValidationState();const c=normalizeCode(code);return (state.players||[]).find(p=>p.validationEventId===state.eventId&&normalizeCode(p.validationCode)===c)||null}
  function logValidation({player,staff,action,status,table=null,seat=null,reason=''}){ensureValidationState();const row={id:'val-'+Date.now()+'-'+Math.random().toString(36).slice(2,6),eventId:state.eventId,playerId:player?.id||null,playerName:player?.name||'',code:player?.validationCode||'',staffId:staff?.id||null,staffName:staff?.name||'',staffRole:staff?.role||'',action,status,table,seat,reason,createdAt:Date.now()};state.validationLog.unshift(row);auditEvent('VALIDATION_CODE_USED',{playerId:row.playerId,staffId:row.staffId,action,status,table,seat,reason,source:'VALIDATION_CODE'});return row}
  function validateCodeUse({code,staff,table,action='SEAT'}){ensureValidationState();const p=validationPlayerByCode(code);if(!staff)return{ok:false,error:'STAFF não autorizado.'};if(!p)return{ok:false,error:'Código não encontrado para o evento atual.'};if(p.status==='eliminated'||p.validationCodeStatus==='INACTIVE')return{ok:false,error:'Código inativo: jogador eliminado.',p};if(action==='SEAT'&&+p.table!==+table)return{ok:false,error:`Jogador atribuído à Mesa ${p.table}, Assento ${p.seat}.`,p};const duplicate=state.validationLog.find(v=>v.playerId===p.id&&v.eventId===state.eventId&&v.action===action&&v.status==='CONFIRMED'&&+v.table===+p.table&&+v.seat===+p.seat);return{ok:true,p,duplicate};}
  function deactivateValidationCode(player,reason='ELIMINATED'){if(!player)return;player.validationCodeStatus='INACTIVE';player.validationCodeInactiveAt=Date.now();player.validationCodeInactiveReason=reason}
  function activateValidationCode(player,{renew=false}={}){if(!player)return;if(renew||player.validationEventId!==state.eventId)player.validationCode=uniqueCode(player);player.validationEventId=state.eventId;player.validationCodeStatus='ACTIVE';delete player.validationCodeInactiveAt;delete player.validationCodeInactiveReason;return player.validationCode}
  window.ValidationCodes={normalizeCode,makeCode,ensurePlayerValidationCode,ensureValidationState,validationPlayerByCode,logValidation,validateCodeUse,deactivateValidationCode,activateValidationCode};
  ensureValidationState();
})();
