(function(){
  const KEY='stackup-player-wallets-v2';
  const CREDIT_FEES_KEY='stackup-credit-fees-v1';
  const DAY=86400000;
  function load(){let data={};try{data=JSON.parse(localStorage.getItem(KEY)||'{}')}catch(e){data={}}return data&&typeof data==='object'&&!Array.isArray(data)?data:{}}
  function save(data){localStorage.setItem(KEY,JSON.stringify(data));window.dispatchEvent(new CustomEvent('stackup-wallet-change'));return data}
  function loadFees(){let rows=[];try{rows=JSON.parse(localStorage.getItem(CREDIT_FEES_KEY)||'[]')}catch(e){rows=[]}return Array.isArray(rows)?rows:[]}
  function saveFees(rows){localStorage.setItem(CREDIT_FEES_KEY,JSON.stringify(rows));window.dispatchEvent(new CustomEvent('stackup-credit-fees-change'));return rows}
  function accountKey(player){if(!player)return'';return String(player.directoryId||player.id||'')}
  function dayKey(ts){const d=new Date(ts||Date.now());return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
  function normalizeAccount(a,player){a=a||{};a.key=a.key||accountKey(player);a.directoryId=a.directoryId||player?.directoryId||'';a.playerId=a.playerId||player?.id||'';a.playerName=player?.name||a.playerName||'';a.balanceBRL=+a.balanceBRL||0;a.movements=Array.isArray(a.movements)?a.movements:[];a.lots=Array.isArray(a.lots)?a.lots:[];a.usageCounters=a.usageCounters&&typeof a.usageCounters==='object'?a.usageCounters:{};a.pixSettlements=Array.isArray(a.pixSettlements)?a.pixSettlements:[];if(!a.lots.length&&a.balanceBRL>0){const oldest=a.movements.slice().reverse().find(m=>['DEPOSIT','PRIZE_CREDIT','BOUNTY_CREDIT','REFUND','ADJUSTMENT_CREDIT'].includes(m.kind));a.lots.push({id:'legacy-'+a.key,remainingBRL:a.balanceBRL,originEventId:oldest?.eventId||'',originDay:dayKey(oldest?.createdAt||Date.now()),createdAt:oldest?.createdAt||Date.now(),kind:'LEGACY'})}return a}
  function ensureAccount(player){const key=accountKey(player);if(!key)return null;const data=load();data[key]=normalizeAccount(data[key],player);save(data);return data[key]}
  function account(player){const key=accountKey(player),data=load();if(!key)return null;if(!data[key])return ensureAccount(player);const before=JSON.stringify(data[key]);data[key]=normalizeAccount(data[key],player);if(JSON.stringify(data[key])!==before)localStorage.setItem(KEY,JSON.stringify(data));return data[key]}
  function addLot(a,value,meta,kind,createdAt){a.lots.push({id:'lot-'+createdAt+'-'+Math.random().toString(36).slice(2,6),remainingBRL:value,originEventId:meta.eventId||'',originDay:dayKey(createdAt),createdAt,kind})}
  function consumeLots(a,value){let left=value;const used=[];a.lots.sort((x,y)=>(x.createdAt||0)-(y.createdAt||0));for(const lot of a.lots){if(left<=0)break;const available=Math.max(0,+lot.remainingBRL||0);if(!available)continue;const take=Math.min(available,left);lot.remainingBRL=available-take;left-=take;used.push({...lot,usedBRL:take})}a.lots=a.lots.filter(l=>(+l.remainingBRL||0)>0.000001);return{ok:left<=0.000001,used}}
  function simulateLots(a,value){let left=value;const used=[];for(const lot of a.lots.slice().sort((x,y)=>(x.createdAt||0)-(y.createdAt||0))){if(left<=0)break;const available=Math.max(0,+lot.remainingBRL||0);if(!available)continue;const take=Math.min(available,left);left-=take;used.push({...lot,usedBRL:take})}return{ok:left<=0.000001,used}}
  function feeFamily(type){if(['REBUY','DOUBLE_REBUY'].includes(type))return'REBUY';if(type==='REENTRY')return'REENTRY';if(type==='ADDON')return'ADDON';return type}
  function feeCodeFor(type){if(type==='ENTRY')return'CROSS_EVENT_BUYIN';if(['REBUY','DOUBLE_REBUY'].includes(type))return'FIRST_REBUY';if(type==='REENTRY')return'FIRST_REENTRY';if(type==='ADDON')return'FIRST_ADDON';return''}
  function configuredRate(type,cfg){const p=cfg?.feePolicy||{};if(type==='ENTRY')return Math.max(0,+p.crossEventBuyinPct||0)/100;if(['REBUY','DOUBLE_REBUY'].includes(type))return Math.max(0,+p.firstRebuyPct||0)/100;if(type==='REENTRY')return Math.max(0,+p.firstReentryPct||0)/100;if(type==='ADDON')return Math.max(0,+p.firstAddonPct||0)/100;return 0}
  function feeQuote(player,valueBRL,meta={}){processExpiredCredits([player]);const a=account(player),cfg=window.StackupFinance?.load?.()||{};if(!a)return{rate:0,feeBRL:0,totalDebitBRL:valueBRL,crossEvent:false};const eventId=String(meta.eventId||''),sim=simulateLots(a,valueBRL);const sameEvent=sim.ok&&sim.used.length>0&&sim.used.every(l=>String(l.originEventId||'')===eventId);if(sameEvent)return{rate:0,feeBRL:0,totalDebitBRL:valueBRL,crossEvent:false,reason:'MESMO TORNEIO • SEM TAXA'};const type=String(meta.type||meta.reference||'').toUpperCase(),code=feeCodeFor(type);let rate=0,reason='SEM TAXA';if(code&&window.StackupFinance?.feeWaived?.(player,code,cfg))reason='TAXA REMOVIDA PELO GESTOR';else if(type==='ENTRY'){rate=configuredRate(type,cfg);reason='CRÉDITO DE OUTRO EVENTO • BUY-IN'}else if(['REBUY','DOUBLE_REBUY','REENTRY','ADDON'].includes(type)){const family=feeFamily(type),counterKey=`${eventId}:${family}`,count=+a.usageCounters[counterKey]||0;if(count===0){rate=configuredRate(type,cfg);reason=`CRÉDITO DE OUTRO EVENTO • PRIMEIRO ${family}`}else reason=`${family} SUBSEQUENTE • SEM TAXA`}const feeBRL=Math.round((valueBRL*rate+Number.EPSILON)*100)/100;return{rate,feeBRL,totalDebitBRL:valueBRL+feeBRL,crossEvent:true,reason,type,eventId,feeCode:code}}
  function recordFee(player,quote,meta){if(!quote.feeBRL)return null;const rows=loadFees(),row={id:'credit-fee-'+Date.now()+'-'+Math.random().toString(36).slice(2,6),playerKey:accountKey(player),playerName:player?.name||'',eventId:meta.eventId||'',type:meta.type||'',operationBRL:+meta.operationBRL||0,rate:quote.rate,feeBRL:quote.feeBRL,reason:quote.reason,createdAt:Date.now()};rows.unshift(row);saveFees(rows);return row}
  function move(player,{kind,valueBRL,reference='',eventId='',source='',meta={}}){const key=accountKey(player);if(!key)return{ok:false,error:'JOGADOR SEM IDENTIFICADOR DE PLAYER CREDIT.'};const data=load();const a=normalizeAccount(data[key],player),value=Math.max(0,+valueBRL||0);if(!value)return{ok:false,error:'VALOR INVÁLIDO.'};const credit=['DEPOSIT','PRIZE_CREDIT','BOUNTY_CREDIT','REFUND','ADJUSTMENT_CREDIT'].includes(kind),debit=['PURCHASE','WITHDRAWAL','ADJUSTMENT_DEBIT'].includes(kind);if(!credit&&!debit)return{ok:false,error:'TIPO DE MOVIMENTAÇÃO INVÁLIDO.'};if(debit&&a.balanceBRL<value)return{ok:false,error:'SALDO INSUFICIENTE.',balance:a.balanceBRL};const now=Date.now();if(debit){const c=consumeLots(a,value);if(!c.ok)return{ok:false,error:'SALDO INSUFICIENTE.'}}else addLot(a,value,{...meta,eventId},kind,now);a.balanceBRL+=(credit?value:-value);const row={id:'wallet-'+now+'-'+Math.random().toString(36).slice(2,7),kind,valueBRL:value,balanceAfterBRL:a.balanceBRL,reference,eventId,source,meta,createdAt:now};a.movements.unshift(row);data[key]=a;save(data);return{ok:true,account:a,movement:row}}
  function deposit(player,valueBRL,meta={}){return move(player,{kind:'DEPOSIT',valueBRL,reference:meta.reference||'DEPÓSITO',eventId:meta.eventId||'',source:meta.source||'PLAYER CREDIT',meta})}
  function purchase(player,valueBRL,meta={}){const amount=Math.max(0,+valueBRL||0),q=feeQuote(player,amount,meta),a=account(player);if(!a)return{ok:false,error:'JOGADOR SEM PLAYER CREDIT.'};if(a.balanceBRL<q.totalDebitBRL)return{ok:false,error:`SALDO INSUFICIENTE. NECESSÁRIO R$ ${q.totalDebitBRL.toFixed(2).replace('.',',')} INCLUINDO TAXA.`,balance:a.balanceBRL,quote:q};const out=move(player,{kind:'PURCHASE',valueBRL:q.totalDebitBRL,reference:meta.reference||meta.type||'COMPRA',eventId:meta.eventId||'',source:meta.source||'PLAYER CREDIT',meta:{...meta,operationBRL:amount,creditFeeBRL:q.feeBRL,creditFeeRate:q.rate,creditFeeReason:q.reason}});if(!out.ok)return out;const data=load(),acc=normalizeAccount(data[accountKey(player)],player),family=feeFamily(String(meta.type||'').toUpperCase());if(q.crossEvent&&['REBUY','DOUBLE_REBUY','REENTRY','ADDON'].includes(String(meta.type||'').toUpperCase())){const k=`${meta.eventId||''}:${family}`;acc.usageCounters[k]=(+acc.usageCounters[k]||0)+1;data[acc.key]=acc;save(data)}const feeRow=recordFee(player,q,{...meta,operationBRL:amount});return{...out,operationBRL:amount,feeBRL:q.feeBRL,totalDebitBRL:q.totalDebitBRL,feeRate:q.rate,feeReason:q.reason,creditFee:feeRow}}
  function prize(player,valueBRL,meta={}){return move(player,{kind:'PRIZE_CREDIT',valueBRL,reference:meta.reference||'PREMIAÇÃO',eventId:meta.eventId||'',source:meta.source||'PLAYER CREDIT',meta})}
  function bounty(player,valueBRL,meta={}){return move(player,{kind:'BOUNTY_CREDIT',valueBRL,reference:meta.reference||'BOUNTY',eventId:meta.eventId||'',source:meta.source||'PLAYER CREDIT',meta})}
  function withdraw(player,valueBRL,meta={}){return move(player,{kind:'WITHDRAWAL',valueBRL,reference:meta.reference||'SAQUE / TROCO',eventId:meta.eventId||'',source:meta.source||'PLAYER CREDIT',meta})}
  function processExpiredCredits(players){const data=load(),now=Date.now(),feeRows=loadFees(),results=[],cfg=window.StackupFinance?.load?.()||{},list=Array.isArray(players)&&players.length?players:Object.values(data).map(a=>({id:a.playerId||a.key,directoryId:a.directoryId||a.key,name:a.playerName||''}));for(const p of list){const key=accountKey(p),a=key?normalizeAccount(data[key],p):null;if(!a||a.balanceBRL<=0)continue;const oldest=a.lots.filter(l=>(+l.remainingBRL||0)>0).sort((x,y)=>(x.createdAt||0)-(y.createdAt||0))[0];if(!oldest||now-(oldest.createdAt||now)<=5*DAY)continue;const gross=a.balanceBRL,waived=window.StackupFinance?.feeWaived?.(p,'EXPIRY',cfg),rate=waived?0:Math.max(0,+cfg.feePolicy?.expiryPct||0)/100,fee=Math.round((gross*rate+Number.EPSILON)*100)/100,pix=Math.max(0,gross-fee);consumeLots(a,gross);a.balanceBRL=0;const settlement={id:'pix-settlement-'+now+'-'+Math.random().toString(36).slice(2,6),grossBRL:gross,feeBRL:fee,pixBRL:pix,status:'PIX_PENDING',reason:waived?'PLAYER CREDIT +5 DIAS • TAXA REMOVIDA':'PLAYER CREDIT ACIMA DE 5 DIAS',createdAt:now};a.pixSettlements.unshift(settlement);a.movements.unshift({id:'wallet-'+now+'-'+Math.random().toString(36).slice(2,7),kind:'WITHDRAWAL',valueBRL:gross,balanceAfterBRL:0,reference:'SAÍDA AUTOMÁTICA APÓS 5 DIAS',eventId:'',source:'PLAYER CREDIT AUTO SETTLEMENT',meta:{feeBRL:fee,pixBRL:pix,status:'PIX_PENDING'},createdAt:now});if(fee>0)feeRows.unshift({id:'credit-fee-'+now+'-'+Math.random().toString(36).slice(2,6),playerKey:key,playerName:p.name||a.playerName||'',eventId:'',type:'EXPIRATION',operationBRL:gross,rate,feeBRL:fee,reason:'CRÉDITO MANTIDO POR MAIS DE 5 DIAS',createdAt:now});data[key]=a;results.push({player:p,account:a,settlement})}if(results.length){save(data);saveFees(feeRows)}return results}
  window.StackupWallet={KEY,CREDIT_FEES_KEY,load,save,loadFees,saveFees,accountKey,ensureAccount,account,move,deposit,purchase,prize,bounty,withdraw,feeQuote,processExpiredCredits,dayKey};
})();