const fs=require('fs');
const path=require('path');
const i18n=require('../app-language.js');
require('../app-language-extra.js');
require('../app-language-final.js');
require('../app-language-qa.js');
require('../app-language-alerts-v1.js');
require('../app-language-ranking-v1.js');

const ROOT=path.resolve(__dirname,'..');
const BRAND="STACKUP HOLD'EM ENTERPRISE";
const EXCLUDE=new Set(['node_modules','.git','.github','tests','tools']);
const EXT=new Set(['.html','.js']);
const SKIP_FILES=new Set(['app-language.js','app-language-extra.js','app-language-final.js','app-language-qa.js','app-language-alerts-v1.js','app-language-ranking-v1.js','app-language-spanish-clean-v1.js','screen-message-groups-v12.js','screen-message-spanish-runtime-v1.js']);

const residualEn=[
'ALERTA','ALERTAS','SONORO','SONOROS','SONORA','SONORAS','RECADO','RECADOS','VOZ','VOZES','TEXTO','TEXTOS','MENSAGEM','MENSAGENS','SELEÇÃO','ATIVAÇÃO','DESATIVAÇÃO','GERENCIAMENTO','PERSONALIZADA','PERSONALIZADAS','MOMENTO','MOMENTOS','ESCOLHA','QUANDO','AGORA','DEFINIDO','DEFINIDA','VEICULAR','AGENDAMENTO','ROLAGEM','RESTAREM','CADASTRAR','CADASTRADO','CADASTRADOS','CADASTRADA','CADASTRADAS','CADASTRO','JOGADOR','JOGADORES','TORNEIO','TORNEIOS','CONFIGURAÇÃO','CONFIGURAÇÕES','GESTÃO','OPERAÇÃO','ESTRUTURA','ESTRUTURAS','NÍVEL','NÍVEIS','SELECIONE','SELECIONAR','SELECIONADO','SELECIONADA','SALVAR','SALVO','APAGAR','EXCLUIR','ANTERIOR','VOLTAR','FECHAR','ADICIONAR','REMOVER','ATUALIZAR','RETOMAR','GERAR','LIMPAR','NENHUM','NENHUMA','INFORMAÇÃO','INFORMAÇÕES','PERMISSÃO','PERMISSÕES','FUNÇÃO','FUNÇÕES','TRANSMISSÃO','FINANCEIRO','ASSISTÊNCIA','REGULAMENTO','PONTUAÇÃO','POSIÇÃO','POSIÇÕES','RESUMO','DESCRIÇÃO','OBSERVAÇÃO','OBSERVAÇÕES','ENDEREÇO','CIDADE','PAÍS','QUANTIDADE','MÉDIA','ELIMINAÇÃO','ELIMINAÇÕES','MOVIMENTAÇÃO','MOVIMENTAÇÕES','NECESSÁRIA','NECESSÁRIO','AGUARDANDO','DISPONÍVEL','DISPONÍVEIS','INSCRIÇÕES','PREMIAÇÃO','COLOCAÇÕES','TAXAS','RECORRENTE','DOBRAR','FICHAS','CADEIRA','ASSENTO','COMPOSIÇÃO','CATÁLOGO','RELATÓRIO','RELATÓRIOS','DADOS','OPERACIONAIS','INTERPRETAÇÃO','EQUIPE','IDIOMA','IDIOMAS','TELA','TELAS','CAIXA','CARTEIRA','PAGAMENTOS','SALDOS','CRÉDITOS','AVISOS','CADASTROS','CONSULTAR','CRIADOS','VALIDADOS','PADRÕES','FUNDO','SECUNDÁRIO','RELÓGIO','EVOLUÇÃO','ARREDONDADA','RETA','SEGMENTADA','UTILIZADO','UTILIZADA','ALTERAÇÃO','NASCIMENTO','TELEFONE','SALA','DIGITE','MOSTRADO','CELULAR','GESTOR','RECONHEÇA','REVISE','APOIO','ANÁLISE','ROTINAS','DÚVIDAS','REGISTRE','TROCAR','PRESENÇA','TRANSFERÊNCIA','INVALIDADO','PRECISA','NOVAMENTE','RECEBIDO','PERMANECE','ALTERADA','CRIAÇÃO','PROCURE','ELIMINADO','DEVE','EXIGE','OPERADOR','AÇÃO','EXECUTÁVEL','MUDOU','AUDITORIA','LANÇAMENTO','PAISAGEM','INSCRIÇÃO','VALIDAÇÃO','PRECISÃO','REVISÁVEL','DETECÇÃO','CONJUNTO','ETAPA','ENVIO','EXTRATO','PREENCHIMENTO','VERIFICAÇÕES','SEGURANÇA','FIDELIDADE','PROMOÇÕES','NOVIDADES','ENFILEIRAR','TÍTULO','MEMBROS','GERENCIE','SOLICITAÇÃO','ATENDIMENTO','CHAMADO','SESSÃO','APARELHO','CONFIRA','ATRIBUÍDO','VALIDAÇÕES','LIBERAÇÃO','INDICADORES','MASCULINA','FEMININA','ATIVO','ATIVOS','ATIVA','ATIVAS','INATIVO','INATIVOS','ABRIR','CRIAR','EDITAR','CONFIRMAR','CONCLUIR','TESTAR','FAIXA','FORMA','INDEPENDENTE','DO','DA','DOS','DAS','DE','PARA','COM','SEM','AO','AOS','NA','NAS','NO','NOS','POR','PELO','PELA','PELOS','PELAS','NÃO','JÁ','NESTE','NESTA','DESTE','DESTA','QUE','SERÁ','AS','OS','UM','UMA','E'
];
const residualEs=['CADASTRAR','CADASTRADO','CADASTRADOS','CADASTRADA','CADASTRADAS','CADASTRO','JOGADOR','JOGADORES','TORNEIO','TORNEIOS','CONFIGURAÇÃO','CONFIGURAÇÕES','GESTÃO','OPERAÇÃO','ESTRUTURA','ESTRUTURAS','NÍVEL','NÍVEIS','SELECIONE','SELECIONAR','SELECIONADO','SELECIONADA','SALVAR','SALVO','APAGAR','VOLTAR','FECHAR','ADICIONAR','REMOVER','ATUALIZAR','RETOMAR','LIMPAR','NENHUM','NENHUMA','INFORMAÇÃO','INFORMAÇÕES','PERMISSÃO','PERMISSÕES','FUNÇÃO','FUNÇÕES','ACESSO','ACESSOS','TRANSMISSÃO','PONTUAÇÃO','POSIÇÃO','POSIÇÕES','RESUMO','DESCRIÇÃO','OBSERVAÇÃO','OBSERVAÇÕES','ENDEREÇO','CIDADE','QUANTIDADE','MÉDIA','ELIMINAÇÃO','ELIMINAÇÕES','MOVIMENTAÇÃO','MOVIMENTAÇÕES','NECESSÁRIA','NECESSÁRIO','AGUARDANDO','DISPONÍVEL','DISPONÍVEIS','INSCRIÇÕES','PREMIAÇÃO','COLOCAÇÕES','TAXAS','DOBRAR','CADEIRA','ASSENTO','COMPOSIÇÃO','RELATÓRIOS','OPERACIONAIS','INTERPRETAÇÃO','EQUIPE','TELA','TELAS','CAIXA','CARTEIRA','MENSAGENS','CADASTROS','PADRÕES','FUNDO','RELÓGIO','EVOLUÇÃO','ESCOLHA','ALTERAÇÃO','NASCIMENTO','TELEFONE','RECONHEÇA','APOIO','ANÁLISE','DÚVIDAS','TROCAR','PRESENÇA','TRANSFERÊNCIA','PRECISA','NOVAMENTE','RECEBIDO','CRIAÇÃO','PROCURE','AÇÃO','MUDOU','AUDITORIA','LANÇAMENTO','PAISAGEM','INSCRIÇÃO','VALIDAÇÃO','PRECISÃO','REVISÁVEL','DETECÇÃO','ENVIO','EXTRATO','PREENCHIMENTO','VERIFICAÇÕES','SEGURANÇA','PROMOÇÕES','NOVIDADES','ENFILEIRAR','MEMBROS','GERENCIE','SOLICITAÇÃO','ATENDIMENTO','CHAMADO','APARELHO','CONFIRA','ATRIBUÍDO','VALIDAÇÕES','LIBERAÇÃO','ATIVAÇÃO','DESATIVAÇÃO','GERENCIAMENTO','PERSONALIZADAS','ROLAGEM','VEICULAR','AGENDAMENTO','RESTAREM','DO','DA','DOS','DAS','COM','SEM','EM','NÃO','JÁ','NESTE','NESTA','DESTE','DESTA'];
const esc=s=>String(s).replace(/[.*+?^${}()|[\]\\]/g,'\\$&');
const hasTerm=(text,terms)=>terms.some(t=>new RegExp(`(^|[^\\p{L}\\p{N}_])${esc(t)}(?=$|[^\\p{L}\\p{N}_])`,'u').test(text));
const clean=s=>String(s||'').replace(/\\n/g,' ').replace(/\s+/g,' ').trim();
const looksUi=s=>{const t=clean(s);if(t.length<2||t.length>360)return false;if(/https?:\/\//i.test(t)||/\$\{|<\/?[a-z]|=>|===|!==|&&|\|\||\.value\b|\.textContent\b|\.innerHTML\b|\b(function|const|let|var|return|if|else|for|while|querySelector|classList|dataset|localStorage|document|window)\b/i.test(t))return false;return /[A-Za-zÀ-ÿ]/.test(t)};
function walk(dir,out=[]){for(const ent of fs.readdirSync(dir,{withFileTypes:true})){if(EXCLUDE.has(ent.name))continue;const p=path.join(dir,ent.name);if(ent.isDirectory())walk(p,out);else if(EXT.has(path.extname(ent.name))&&!SKIP_FILES.has(ent.name))out.push(p)}return out}
function extractHtml(src){const out=[];const textRx=/>\s*([^<>]+?)\s*</g;let m;while((m=textRx.exec(src)))out.push(m[1]);const attrRx=/(?:placeholder|title|aria-label|value)\s*=\s*["']([^"']+)["']/gi;while((m=attrRx.exec(src)))out.push(m[1]);return out}
function extractJs(src){const out=[];const rx=/'([^'\n]{2,360})'|"([^"\n]{2,360})"|`([^`\n]{2,360})`/g;let m;while((m=rx.exec(src)))out.push(m[1]||m[2]||m[3]||'');return out}
const files=walk(ROOT),missingLoader=[],failures=[];let candidates=0;
for(const file of files){const rel=path.relative(ROOT,file).replace(/\\/g,'/'),src=fs.readFileSync(file,'utf8');if(rel.endsWith('.html')){const isRedirectOnly=/location\.(?:replace|assign)\s*\(/.test(src)&&!/<(?:main|section|form|button|input|select|textarea|a)\b/i.test(src);const hasLoader=/shared\.js|app-language\.js|input-masks\.js|ui-standard\.js|auth-engine\.js|<iframe\b/i.test(src)||isRedirectOnly;if(!hasLoader)missingLoader.push(rel)}const strings=rel.endsWith('.html')?extractHtml(src):extractJs(src);for(const raw of strings){const text=clean(raw);if(!looksUi(text))continue;candidates++;const en=clean(i18n.translateString(text,'en')),es=clean(i18n.translateString(text,'es'));const cen=en.replaceAll(BRAND,''),ces=es.replaceAll(BRAND,'');if(hasTerm(cen.toUpperCase(),residualEn))failures.push(`${rel} :: EN :: ${text} => ${en}`);if(hasTerm(ces.toUpperCase(),residualEs))failures.push(`${rel} :: ES :: ${text} => ${es}`)}}
if(!/^3\./.test(i18n.version||''))failures.push(`VERSÃO DO MOTOR INESPERADA: ${i18n.version}`);const engine=fs.readFileSync(path.join(ROOT,'app-language.js'),'utf8');if(!/characterData:true/.test(engine))failures.push('MOTOR NÃO OBSERVA ALTERAÇÕES DE TEXTO DINÂMICAS.');if(!/iframe/i.test(engine))failures.push('MOTOR NÃO COBRE IFRAMES SAME-ORIGIN.');if(missingLoader.length)failures.push(`TELAS SEM CARREGAMENTO GLOBAL DE IDIOMA: ${missingLoader.join(', ')}`);const unique=[...new Set(failures)];if(unique.length){console.error(`LANGUAGE DEEP AUDIT FALHOU: ${unique.length} PROBLEMA(S) EM ${candidates} STRING(S) REAIS DE UI.`);unique.slice(0,1000).forEach(x=>console.error(' - '+x));if(unique.length>1000)console.error(` - ... ${unique.length-1000} PROBLEMA(S) ADICIONAIS`);process.exit(1)}console.log(`LANGUAGE DEEP AUDIT OK: ${files.length} ARQUIVOS, ${candidates} STRING(S) REAIS DE UI, PT/EN/ES VERIFICADOS PALAVRA POR PALAVRA, SEM TRADUÇÕES HÍBRIDAS.`);